version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://crmuser:crmpassword@db:5432/crmdb
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=crmuser
      - POSTGRES_PASSWORD=crmpassword
      - POSTGRES_DB=crmdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
